<a href="https://colab.research.google.com/github/hrithikpurwar/ML/blob/main/ClassificationRandomForestAndDecisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [20]:
df=pd.read_csv('/content/Social_Network_Ads.csv',sep=',')

In [3]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
df.shape

(400, 5)

In [21]:
df.drop(['User ID'], axis=1, inplace=True)
df.head(15)


Gender  Age  EstimatedSalary  Purchased
0     Male   19            19000          0
1     Male   35            20000          0
2   Female   26            43000          0
3   Female   27            57000          0
4     Male   19            76000          0
5     Male   27            58000          0
6   Female   27            84000          0
7   Female   32           150000          1
8     Male   25            33000          0
9   Female   35            65000          0
10  Female   26            80000          0
11  Female   26            52000          0
12    Male   20            86000          0
13    Male   32            18000          0
14    Male   18            82000          0

In [22]:
df=pd.get_dummies(df,drop_first=True)

In [23]:
df.head()

Age  EstimatedSalary  Purchased  Gender_Male
0   19            19000          0            1
1   35            20000          0            1
2   26            43000          0            0
3   27            57000          0            0
4   19            76000          0            1

In [8]:
df.isnull().sum()

Age                0
EstimatedSalary    0
Purchased          0
Gender_Male        0
dtype: int64

In [9]:
df.dtypes

Age                int64
EstimatedSalary    int64
Purchased          int64
Gender_Male        uint8
dtype: object

In [24]:
Y=pd.DataFrame(df['Purchased'])
df.drop(['Purchased'], axis=1, inplace=True)


In [25]:
X=df

In [26]:
X

Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [27]:
Y

Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

In [29]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(280, 3)
(280, 1)
(120, 3)
(120, 1)


In [30]:
#we dont need feature scaling on decision trees

In [31]:
from sklearn.tree import DecisionTreeClassifier
classifier1=DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier1.fit(X_train,Y_train)
Y_pred1=classifier1.predict(X_test)

In [32]:
from sklearn.metrics import confusion_matrix
cn=confusion_matrix(Y_test,Y_pred1) #8+3=11 incorrect prediction
print(cn)

[[71  8]
 [ 3 38]]


In [33]:
 from sklearn.metrics import accuracy_score
 score=accuracy_score(Y_test, Y_pred1)*100
 print('accuracy=',score,'%')

accuracy= 90.83333333333333 %


In [37]:
from sklearn.ensemble import RandomForestClassifier
classifier2=RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
classifier2.fit(X_train,Y_train)
Y_pred2=classifier2.predict(X_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [38]:
cn2=confusion_matrix(Y_test,Y_pred2) #6+7=13 incorrect prediction
print(cn2)

[[72  7]
 [ 6 35]]


In [39]:
from sklearn.ensemble import RandomForestClassifier
classifier3=RandomForestClassifier(n_estimators=500, criterion='entropy', random_state=0)
classifier3.fit(X_train,Y_train)
Y_pred3=classifier3.predict(X_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [40]:
cn3=confusion_matrix(Y_test,Y_pred3) #6+5=11 incorrect prediction
print(cn3)

[[73  6]
 [ 5 36]]


In [41]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [42]:
from sklearn.tree import DecisionTreeClassifier
classifier1=DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier1.fit(X_train,Y_train)
Y_pred1=classifier1.predict(X_test)

In [43]:
from sklearn.metrics import confusion_matrix
cn=confusion_matrix(Y_test,Y_pred1) #8+4=12 incorrect prediction
print(cn)

[[71  8]
 [ 4 37]]


In [44]:
from sklearn.ensemble import RandomForestClassifier
classifier2=RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
classifier2.fit(X_train,Y_train)
Y_pred2=classifier2.predict(X_test)
cn2=confusion_matrix(Y_test,Y_pred2) #6+6=12 incorrect prediction
print(cn2)

[[73  6]
 [ 6 35]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [45]:
from sklearn.ensemble import RandomForestClassifier
classifier3=RandomForestClassifier(n_estimators=500, criterion='entropy', random_state=0)
classifier3.fit(X_train,Y_train)
Y_pred3=classifier3.predict(X_test)
cn3=confusion_matrix(Y_test,Y_pred3) #5+5=10 incorrect prediction
print(cn3)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


[[74  5]
 [ 5 36]]
