<a href="https://colab.research.google.com/github/hrithikpurwar/ML/blob/main/KernelSVMClassifier%2BallKernel%2BKNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
df=pd.read_csv('/content/Social_Network_Ads.csv',sep=',')

In [7]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [8]:
df.shape

(400, 5)

In [9]:
df.drop(['User ID'], axis=1, inplace=True)
df.head(15)

Gender  Age  EstimatedSalary  Purchased
0     Male   19            19000          0
1     Male   35            20000          0
2   Female   26            43000          0
3   Female   27            57000          0
4     Male   19            76000          0
5     Male   27            58000          0
6   Female   27            84000          0
7   Female   32           150000          1
8     Male   25            33000          0
9   Female   35            65000          0
10  Female   26            80000          0
11  Female   26            52000          0
12    Male   20            86000          0
13    Male   32            18000          0
14    Male   18            82000          0

In [10]:
df=pd.get_dummies(df,drop_first=True)

In [11]:
df.head()

Age  EstimatedSalary  Purchased  Gender_Male
0   19            19000          0            1
1   35            20000          0            1
2   26            43000          0            0
3   27            57000          0            0
4   19            76000          0            1

In [12]:
df['Gender']=df['Gender_Male']
df.head()

Age  EstimatedSalary  Purchased  Gender_Male  Gender
0   19            19000          0            1       1
1   35            20000          0            1       1
2   26            43000          0            0       0
3   27            57000          0            0       0
4   19            76000          0            1       1

In [13]:
df['Purchase']=df['Purchased']
df.head()

Age  EstimatedSalary  Purchased  Gender_Male  Gender  Purchase
0   19            19000          0            1       1         0
1   35            20000          0            1       1         0
2   26            43000          0            0       0         0
3   27            57000          0            0       0         0
4   19            76000          0            1       1         0

In [14]:
df=df.drop(['Purchased'],axis=1)
df=df.drop(['Gender_Male'],axis=1)
df.head()

Age  EstimatedSalary  Gender  Purchase
0   19            19000       1         0
1   35            20000       1         0
2   26            43000       0         0
3   27            57000       0         0
4   19            76000       1         0

In [15]:
df.isnull().sum()

Age                0
EstimatedSalary    0
Gender             0
Purchase           0
dtype: int64

In [16]:
df.dtypes

Age                int64
EstimatedSalary    int64
Gender             uint8
Purchase           int64
dtype: object

In [17]:
X=df.iloc[:,:-1]
Y=df.iloc[:,-1:]


In [18]:
X.head()

Age  EstimatedSalary  Gender
0   19            19000       1
1   35            20000       1
2   26            43000       0
3   27            57000       0
4   19            76000       1

In [19]:
Y.head()

Purchase
0         0
1         0
2         0
3         0
4         0

In [20]:
Y.tail()

Purchase
395         1
396         1
397         1
398         0
399         1

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

In [22]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(280, 3)
(280, 1)
(120, 3)
(120, 1)


In [23]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [24]:
from sklearn.svm import SVC
classifier1=SVC(kernel='rbf')
classifier1.fit(X_train,Y_train)
Y_pred1=classifier1.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [25]:
from sklearn.metrics import confusion_matrix
cn=confusion_matrix(Y_test,Y_pred1) #4+5=9 incorrect prediction
print(cn)

[[74  5]
 [ 4 37]]


In [26]:
from sklearn.svm import SVC
classifier2=SVC(kernel='linear')
classifier2.fit(X_train,Y_train)
Y_pred2=classifier2.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [27]:

cn2=confusion_matrix(Y_test,Y_pred2) #13+3=16 incorrect prediction
print(cn2)

[[76  3]
 [13 28]]


In [28]:
classifier3=SVC(kernel='poly')
classifier3.fit(X_train,Y_train)
Y_pred3=classifier3.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [29]:
cn3=confusion_matrix(Y_test,Y_pred3) #12+4=16 incorrect prediction
print(cn3)

[[75  4]
 [12 29]]


In [31]:
from sklearn.neighbors import KNeighborsClassifier
classifier4=KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier4.fit(X_train,Y_train)
Y_pred4=classifier4.predict(X_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [32]:
cn4=confusion_matrix(Y_test,Y_pred4) #4+6=10 incorrect prediction
print(cn4)

[[73  6]
 [ 4 37]]


In [33]:
 from sklearn.metrics import accuracy_score
 score=accuracy_score(Y_test, Y_pred1)*100
 print('accuracy=',score,'%')

accuracy= 92.5 %


In [34]:
 score=accuracy_score(Y_test, Y_pred2)*100
 print('accuracy=',score,'%')

accuracy= 86.66666666666667 %


In [35]:
 score=accuracy_score(Y_test, Y_pred3)*100
 print('accuracy=',score,'%')

accuracy= 86.66666666666667 %


In [36]:
 score=accuracy_score(Y_test, Y_pred4)*100
 print('accuracy=',score,'%')

accuracy= 91.66666666666666 %


In [38]:
print(classifier1.predict(sc_X.transform([[19,19000,1]])))

[0]
